// Generated by https://quicktype.io
import 'dart:convert';

import 'package:flutter/material.dart';

class Users{

  List<UserModel> listUser =  [];

  Users();

  Users.fromJsontoList(List<dynamic> jsonlist ){
    if (jsonlist == null) return ;

    for (var item in jsonlist) {
      final user = new UserModel.fromJsontoMap(item);
      listUser.add(user);
    }
  }

}

class UserModel {
  
  int id = 0;
  String username = "";
  String nombre = "";
  String contrasena = "";
  int estado = 0;
  String avatar = "";

  UserModel({
    this.id           = 0,
    this.username     = "",
    this.nombre       = "",
    this.contrasena   = "",
    this.estado       = 0,
    this.avatar       = "",
  });

  UserModel.fromJsontoMap(Map<String, dynamic> json){
    id = json["id"];
    username  = json["username"];
    nombre = json["nombre"];
    contrasena = json["contrasena"];
    estado = json["estado"];
    avatar = json["avatar"];
    
  }

  getPosterAvatar() {
    if (avatar == null) {
      return 'https://suhsport.es/img/noImage.jpg';
    } else {
      return avatar;
    }
  }


}
